host: 0.0.0.0 # listen address
port: 8000 # listen port
log_level: INFO # log level
server_url: http://jenkins-gitlab-integrator.example.local:8000 #server url for hooks (need for auto create webhooks)
gitlab_webhook_token: adEleRYsiViB1_34 #token for auth gitlab webhooks (Secret Token, Private-Token header)

#generate secret
#from cryptography.fernet import Fernet
#Fernet.generate_key()
session_secret: N5I6xGINvJ6RigIwd_SX7nHM4J7zYc6ONx6MGH3F__o= # salt for cookies
#user list
users:
  - username: root
    password: root
    permission: [ADMIN_UI]

#mysql connection, same as alembic.ini
mysql:
  db: jenkins_integrator
  host: 127.0.0.1
  user: root
  password: ''
  port: 3306
  minsize: 5
  maxsize: 5

#gitlab api config
gitlab:
  url: https://gitlab.example.local #gitlab url
  access_token: adEleRYsiViB #gitlab user api token (look to gitlab docs)

#background workers config
workers:
  enable: yes #enable or disable run workers
  max_attempts: 1400 # how many try for do task
  scan_timeout: 60 # period between task run

jenkins: #settings for jenkins
  user_id: sergei.kravchuk #jenkins user
  api_token: 2342b01c03caaa0465d144e310893ba9 # jenkins api token
